[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lyart_spec"
version = "0.1.0"
description = "A lightweight Python module for evaluating Lyman-alpha spectra with radiative transfer under different simple geometries, recoil, velocity gradients."
readme = "README.md"
requires-python = ">=3.8.20"
license = { text = "MIT License" }
authors = [{name = "Pengfei Li", email = "Pengfei.Li@utah.edu"}]
dependencies = ["numpy>=1.24.4", "scipy>=1.10.1", "notebook>=6.5.7", "matplotlib>3.7.3"]

[tool.setuptools.packages.find]
where = ["lyart_spec"]

